import type { TemplateDocument } from "@/components/documents/pdf-styles";

/* ================================================================
   CLIENT DOCUMENT CONTENT
   8 template documents for client-facing operations
   ================================================================ */

export const termsAndConditions: TemplateDocument = {
  title: "Terms & Conditions",
  subtitle: "Standard Service Agreement",
  ref: "SD-TC-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: 'These Terms & Conditions ("Terms") govern all services provided by Keenan Husselmann, trading as Swift Designz ("Service Provider", "we", "us"), to clients ("you", "Client"). By accepting a quotation, signing a Proceed to Build document, or making a deposit payment, you unconditionally agree to these Terms.',
    },
    {
      type: "section",
      number: "01",
      title: "Parties & Nature of Engagement",
      bullets: [
        "The Service Provider is Keenan Husselmann, an individual freelancer trading under the name Swift Designz. Swift Designz is not a registered company.",
        "Services are provided remotely and worldwide. No physical address is maintained.",
        "All formal communications, agreements, and invoices are issued by Keenan Husselmann in their personal capacity as a freelancer.",
        "The Client is the individual or organisation that accepts a quotation and engages Swift Designz for services.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Services Offered",
      body: "Swift Designz offers the following services. Service scope, deliverables, and pricing are defined per project in the associated Quotation document.",
      bullets: [
        "Website Development \u2014 Custom websites (Starter from R2,500 \u00b7 Professional from R5,000 \u00b7 Premium from R10,000)",
        "E-Commerce Stores \u2014 Shopify and custom store builds (Starter from R4,000 \u00b7 Business from R7,500 \u00b7 Enterprise from R15,000)",
        "App & Software Development \u2014 MVP to enterprise builds (MVP from R5,000 \u00b7 Standard from R12,000 \u00b7 Full-Scale from R25,000)",
        "AI Training \u2014 Individual (30-min sessions) and team (1.5-hour sessions) AI workflow training, workshops, and online seminars",
        "Project Management Training \u2014 Individual coaching, team sessions, and full workshops covering Agile, Scrum, Kanban, and PM tools",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Quotations & Acceptance",
      bullets: [
        "All quotes are valid for 14 calendar days from the date of issue. Prices may change after this period.",
        "Acceptance of a quotation is confirmed by signing the Proceed to Build document or making a deposit payment, whichever occurs first.",
        "Swift Designz reserves the right to decline or modify a quote if the scope changes materially before acceptance.",
        "Quotes are prepared in good faith based on information provided by the client. Incomplete or inaccurate client information may result in revised pricing.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Payment Terms",
      body: "4.1 Standard Terms",
      bullets: [
        "A 50% non-refundable deposit is required before any work commences. Project start date is the date the deposit is confirmed received.",
        "The remaining 50% is due on launch/delivery of the final product, before handover of files, credentials, or go-live.",
        "All payments are in ZAR/NAD (R) via EFT only. No cash, crypto, or third-party apps.",
        "Banking details are provided on all invoices and the Proceed to Build document. Reference must always include the invoice/document number.",
      ],
    },
    {
      type: "section",
      number: "",
      title: "Payment Plans (4.2)",
      bullets: [
        "Standard: 50% deposit + 50% on launch.",
        "2-Month Flex: 50% deposit + 50% in Month 2.",
        "3-Month Ease: 50% deposit + 25% Month 2 + 25% Month 3 (max 3 months from acceptance).",
        "Full Pay (Best Value): 100% upfront. Client receives 2 months free support instead of the standard 1 month.",
        "Payment plans are only available for a maximum of 3 calendar months from the project acceptance date.",
      ],
    },
    {
      type: "section",
      number: "",
      title: "Late Payments (4.3)",
      bullets: [
        "Any payment that is 5 or more business days overdue will result in the forfeiture of the 1-month free post-launch support.",
        "Projects will be paused (not cancelled) during payment delays. Work resumes on receipt of outstanding amounts.",
        "Go-live / delivery will not proceed until all outstanding balances are cleared.",
      ],
    },
    {
      type: "section",
      number: "",
      title: "VAT (4.4)",
      body: "Swift Designz / Keenan Husselmann is not VAT registered. No VAT is charged or claimable on any invoice.",
    },
    {
      type: "section",
      number: "05",
      title: "Project Commencement & Timeline",
      bullets: [
        "Project work commences within 24 hours of confirmed deposit receipt.",
        "Estimated timelines per service are outlined in the quotation. These are estimates only and may vary based on scope complexity and client responsiveness.",
        "The timeline clock pauses where the project is waiting on client-provided assets, feedback, or approvals beyond 7 business days.",
        "Indicative timelines: Starter websites 4 days \u00b7 Professional 8 days \u00b7 Premium 14\u201321 days \u00b7 E-commerce Starter 4 days \u00b7 Business 14 days \u00b7 Enterprise 21 days \u00b7 Apps: architecture-dependent (scoped per project) \u00b7 Training sessions: scheduled per agreement.",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Revisions & Change Requests",
      bullets: [
        "All packages include up to 3 rounds of revisions. A revision round is a set of related changes submitted at one time.",
        "Any work outside the agreed scope, or revisions beyond the included rounds, are considered change requests charged at R350 per hour.",
        "Change requests must be submitted in writing via the Swift Designz Change Request Form (SD-CR-2026).",
        "Swift Designz will provide a time estimate before proceeding with any out-of-scope work. Approval from the client is required before work begins.",
        "Changes to the agreed scope mid-project may affect timelines and pricing. A revised estimate will be provided.",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Client Responsibilities",
      bullets: [
        "Clients are responsible for providing all required content, copy, images, branding, and assets in a timely manner.",
        "Client-provided assets are included at no additional charge. If Swift Designz creates or sources assets, design/sourcing fees apply at R350/hour.",
        "Clients must provide feedback within 7 business days of receiving any draft or preview. Delays beyond this may extend the project timeline.",
        "If a client is unresponsive for 7 or more business days without prior notice, they must appoint a proxy authorised to make project decisions on their behalf.",
        "Clients are responsible for obtaining all third-party licences, permissions, and approvals required for their content (e.g. images, music, trademarks).",
      ],
    },
    {
      type: "section",
      number: "08",
      title: "Domain & Hosting",
      bullets: [
        "Domain registration and hosting are not included in project quotes unless explicitly stated.",
        "Swift Designz facilitates domain and hosting through our partner: IT-Guru (Ambrose \u00b7 ambrose@it-guru.co.za \u00b7 072 962 7608 \u00b7 it-guru.co.za). Costs are quoted separately by IT-Guru.",
        "Clients may arrange their own hosting; Swift Designz will provide assistance during deployment as part of the project scope.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Intellectual Property & Ownership",
      bullets: [
        "Shopify Stores: The Shopify merchant account belongs to the client. Swift Designz provides development services only and retains no ownership of the store platform or products.",
        "Websites & Apps: Swift Designz retains a perpetual non-exclusive licence over the codebase. The client receives a perpetual use licence upon full payment, allowing them to use, modify, and host the product.",
        "Full Code Transfer: A full code ownership transfer (including removal of Swift Designz\u2019s retained licence) is available at an additional cost \u2014 quoted on request.",
        "Client Content: All client-supplied content (text, images, branding) remains the intellectual property of the client.",
        "Portfolio Rights: Swift Designz retains the right to display all completed work in their portfolio, case studies, and promotional materials. Clients may opt out in writing before project launch.",
      ],
    },
    {
      type: "section",
      number: "10",
      title: "Cancellation & Project Abandonment",
      bullets: [
        "The deposit is non-refundable in all circumstances. It compensates Swift Designz for reserved time and work completed to the cancellation point.",
        "If a client wishes to cancel, the project will be paused rather than cancelled. The client retains the option to resume the project at a later date, subject to availability and a potential re-scoping fee.",
        "After 6 months of inactivity (paused project) without communication, Swift Designz reserves the right to formally close the project. Any remaining deposit credit is forfeited.",
        "If a client is unresponsive for 7 consecutive business days, a formal notification will be sent. Continued silence may result in the project being paused until contact is re-established.",
      ],
    },
    {
      type: "section",
      number: "11",
      title: "Post-Launch Support & Warranty",
      bullets: [
        "All completed projects include 1 month of free post-launch support, covering bug fixes and minor adjustments arising from the original scope.",
        "This free support period is forfeited if the final payment is not made on time (5+ business days late).",
        "Full Pay clients receive 2 months of free support as a bonus.",
        "After the free support period, ongoing support is available via the Maintenance Retainer (R800/month).",
        "The free support period covers bugs and issues related to the original build only. New features, content updates, or out-of-scope changes are billed separately.",
      ],
    },
    {
      type: "section",
      number: "12",
      title: "Maintenance Retainer",
      bullets: [
        "The Swift Designz Maintenance Retainer is available at R800/month.",
        "Retainer clients receive access to Swift Designz services at any time during the billing period with no additional hourly fees for maintenance and minor updates.",
        "The retainer covers: bug fixes, content updates, security patches, minor feature additions, and priority support.",
        "Major new features or significant rebuilds are scoped and quoted separately even for retainer clients.",
        "The retainer is billed monthly and may be cancelled with 30 days\u2019 written notice.",
      ],
    },
    {
      type: "section",
      number: "13",
      title: "Training Services (AI & PM)",
      bullets: [
        "All training sessions are conducted remotely via Zoom, Google Meet, or agreed platform.",
        "Individual sessions are 30 minutes. Team sessions are 1.5 hours. Full workshops are quoted per duration.",
        "Clients receive course materials, notes, and resources relevant to the session topic.",
        "Course materials and notes remain the intellectual property of Swift Designz but the client is granted a licence to use them personally/internally.",
        "Session cancellations must be made at least 24 hours in advance. Late cancellations (under 24 hours) may forfeit the session fee.",
        "Recording of sessions requires prior written consent from Swift Designz.",
      ],
    },
    {
      type: "section",
      number: "14",
      title: "Confidentiality",
      body: "Both parties agree to keep confidential any proprietary information, trade secrets, business data, or personal information disclosed during the project. This obligation survives the termination of any agreement. A separate NDA (SD-NDA-2026) may be executed for projects requiring enhanced confidentiality.",
    },
    {
      type: "section",
      number: "15",
      title: "Limitation of Liability",
      bullets: [
        "Swift Designz (Keenan Husselmann) will not be liable for any indirect, incidental, or consequential damages arising from the use of deliverables.",
        "Total liability in any claim shall not exceed the total amount paid by the client for the specific project in question.",
        "Swift Designz is not responsible for third-party service failures (e.g. hosting outages, Shopify platform changes, payment gateway issues).",
        "The client is responsible for maintaining backups of their website and data.",
      ],
    },
    {
      type: "section",
      number: "16",
      title: "Governing Law & Disputes",
      bullets: [
        "These Terms are governed by the laws applicable in the jurisdiction of the Service Provider (Namibia) or as agreed between parties.",
        "Any disputes will first be attempted to be resolved through direct negotiation in good faith.",
        "If a resolution cannot be reached within 30 days of written notice, the matter may be referred to mediation or the relevant small claims / magistrate\u2019s court.",
      ],
    },
    {
      type: "section",
      number: "17",
      title: "Amendments to These Terms",
      body: "Swift Designz reserves the right to update these Terms at any time. The version in effect at the time of project acceptance governs that engagement. The current version is always available at swiftdesignz.co.za and referenced on all project documents as SD-TC-2026.",
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing any Swift Designz project document (Quote, Proceed to Build, or Payment Plan Agreement), or by making a deposit payment, the client unconditionally accepts these Terms & Conditions in full.",
    },
    { type: "signatures", leftLabel: "Client Acknowledgement", rightLabel: "Swift Designz" },
  ],
};

export const nda: TemplateDocument = {
  title: "Non-Disclosure",
  subtitle: "Mutual Confidentiality Agreement",
  ref: "SD-NDA-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: 'This Mutual Non-Disclosure Agreement ("Agreement") is entered into between Keenan Husselmann, trading as Swift Designz ("Disclosing Party / Receiving Party"), and the client identified below. Both parties agree that each will serve as both a Disclosing Party and a Receiving Party.',
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Definitions",
      bullets: [
        '"Confidential Information" \u2014 Any non-public information disclosed by one party to the other, whether in written, oral, electronic, visual, or any other form, that is identified as confidential or would reasonably be understood to be confidential.',
        '"Receiving Party" \u2014 The party that receives Confidential Information from the Disclosing Party.',
        '"Disclosing Party" \u2014 The party that discloses Confidential Information to the Receiving Party.',
        '"Agreement Term" \u2014 The duration of the active project plus 2 (two) years from the project completion or termination date.',
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Confidential Information Covered",
      body: "Confidential Information includes, but is not limited to:",
      bullets: [
        "Client: Business plans, customer data, proprietary processes, trade secrets, financial data, pricing strategies, product roadmaps, and unreleased features or campaigns.",
        "Swift Designz: Development methods, tools, workflows, codebase approaches, template systems, project management techniques, pricing structures, and proprietary software frameworks.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Obligations of Both Parties",
      body: "Each party agrees to:",
      bullets: [
        "Keep all Confidential Information strictly confidential and not disclose it to any third party without prior written consent from the Disclosing Party.",
        "Use Confidential Information solely for the purposes of the project or engagement defined above.",
        "Apply at least the same degree of protection as they apply to their own confidential information, but no less than reasonable care.",
        "Promptly notify the other party if they become aware of any actual or suspected breach of this Agreement.",
        "Limit disclosure to employees, contractors, or advisors who have a strict need to know and are bound by equivalent confidentiality obligations.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Exclusions from Confidentiality",
      body: "The confidentiality obligations do not apply to information that:",
      bullets: [
        "Is or becomes publicly known through no breach of this Agreement.",
        "Was already known to the Receiving Party before disclosure, as evidenced by prior records.",
        "Is independently developed by the Receiving Party without reference to the Confidential Information.",
        "Is required to be disclosed by applicable law, court order, or regulatory authority \u2014 provided the Disclosing Party is notified promptly and given an opportunity to seek a protective order.",
        "Portfolio Exception: Swift Designz retains the right to reference the client\u2019s name, project type, and general outcome (not confidential details) in portfolio and case studies, unless the client opts out in writing before project launch.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Duration",
      body: "This Agreement is effective on the date of signing and remains in force for the duration of the active project, plus two (2) years from the date the project formally concludes or the engagement is terminated \u2014 whichever is later.",
    },
    {
      type: "section",
      number: "06",
      title: "Return or Destruction of Information",
      body: "Upon the completion or termination of this Agreement, each party agrees to promptly return or securely destroy any Confidential Information belonging to the other party, upon written request. Digital files must be deleted from all storage systems, including backups, within 30 days of such a request.",
    },
    {
      type: "section",
      number: "07",
      title: "Remedies for Breach",
      body: "Both parties acknowledge that a breach of this Agreement may cause irreparable harm for which monetary damages alone would be insufficient. In the event of a breach, the injured party shall be entitled to seek immediate injunctive or other equitable relief, in addition to any other remedies available at law. The prevailing party in any legal action to enforce this Agreement shall be entitled to recover reasonable attorney\u2019s fees.",
    },
    {
      type: "section",
      number: "08",
      title: "Governing Law",
      body: "This Agreement shall be governed by the laws of Namibia (or as jointly agreed between both parties). Any disputes that cannot be resolved amicably shall be submitted to the jurisdiction of the relevant competent court.",
    },
    {
      type: "section",
      number: "09",
      title: "Entire Agreement",
      body: "This Agreement constitutes the entire understanding between the parties with respect to its subject matter and supersedes all prior discussions, representations, or agreements. Any amendments must be in writing and signed by both parties. This Agreement may be executed in counterparts, including electronic signatures, each of which shall be deemed an original.",
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing below, both parties confirm that they have read, understood, and agree to be bound by this Non-Disclosure Agreement.",
    },
    { type: "signatures", leftLabel: "Client", rightLabel: "Swift Designz" },
  ],
};

export const clientOnboarding: TemplateDocument = {
  title: "Client Onboarding",
  subtitle: "Welcome to Swift Designz",
  ref: "SD-ON-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "Welcome aboard. Thank you for choosing Swift Designz. This guide walks you through everything you need to know to get your project started smoothly \u2014 the process, what I need from you, timelines, and how we communicate.",
    },
    {
      type: "section",
      number: "01",
      title: "Your Project Journey",
      body: "Every project follows a clear six-step process:",
      bullets: [
        "Step 1: Discovery & Sign-Off \u2014 Quotation accepted, Proceed to Build signed, deposit paid. Project is officially live. Confirmation email within 24 hours.",
        "Step 2: Design & Structure \u2014 Wireframes, design concepts, or technical architecture created. You approve direction before full build begins.",
        "Step 3: Build Phase \u2014 Full development through the agreed scope. Progress check-ins depending on project size.",
        "Step 4: Review & Revisions \u2014 Preview link shared. You review and submit feedback within 7 business days. Up to 3 revision rounds included.",
        "Step 5: Launch / Delivery \u2014 Final payment received, project goes live, files and credentials handed over.",
        "Step 6: Post-Launch Support \u2014 1 month (or 2 for Full Pay) of free support included. Ongoing via R800/month Maintenance Retainer.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "What I Need From You \u2014 Content & Assets",
      body: "Please gather these items as early as possible. Delays in receiving assets may extend your project timeline.",
      bullets: [
        "All page text, body copy, bios, and service descriptions.",
        "Logo in PNG or SVG format (transparent background preferred).",
        "Brand colours (hex codes), reference websites (likes and dislikes).",
        "High-resolution images, product photos, and media files.",
        "Contact details, social media links, and testimonials.",
        "Domain name and login credentials (if existing).",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "E-Commerce Clients \u2014 Additional Requirements",
      bullets: [
        "Shopify or platform login credentials.",
        "Product list with descriptions, pricing, and variants.",
        "Product photos (high-resolution).",
        "Shipping zones, rates, and tax settings.",
        "Refund and return policy text.",
        "Payment gateway preference.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "App & Software Clients \u2014 Additional Requirements",
      bullets: [
        "Core feature list (must-haves vs nice-to-haves).",
        "Target platform (iOS, Android, Web, Desktop).",
        "Target user personas and user flow diagrams (if any).",
        "APIs or third-party integrations required.",
        "Authentication requirements and data structure notes.",
        "Launch and deployment preferences.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Training Clients \u2014 Session Preparation",
      bullets: [
        "Confirm session link and time slot.",
        "Topic or focus area agreed in advance.",
        "Tools to be covered (ChatGPT, Copilot, Gemini, Jira, Trello, etc.).",
        "Number of attendees confirmed (team sessions).",
        "Payment confirmed before the session.",
        "You will receive: course notes, resource lists, prompt templates, and a recording link (where consent was granted).",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Indicative Timelines",
      body: "These are estimates. Final timelines are confirmed in your Proceed to Build document.",
    },
    {
      type: "table",
      headers: ["Service", "Package", "Estimated Duration"],
      rows: [
        ["Website", "Starter", "4 business days"],
        ["Website", "Professional", "8 business days"],
        ["Website", "Premium", "14\u201321 business days"],
        ["E-Commerce", "Starter", "4 business days"],
        ["E-Commerce", "Business", "14 business days"],
        ["E-Commerce", "Enterprise", "21 business days"],
        ["App / Software", "MVP", "Scoped per project"],
        ["App / Software", "Standard", "Scoped per project"],
        ["App / Software", "Full-Scale", "Scoped per project"],
        ["Training", "Individual (30 min)", "Scheduled per agreement"],
        ["Training", "Team (1.5 hr)", "Scheduled per agreement"],
      ],
      colWidths: [30, 30, 40],
    },
    {
      type: "section",
      number: "07",
      title: "Communication Guidelines",
      bullets: [
        "Feedback window: Please respond to review requests within 7 business days. Extended silence may pause the project timeline.",
        "Changes: All change requests must be submitted in writing (email or Change Request Form SD-CR-2026).",
        "Preferred channel: Email is the official channel. Messaging apps may be used for quick questions only \u2014 formal approvals must be via email.",
        "Proxy: If you will be unavailable for 7+ business days, please nominate a proxy who can approve decisions on your behalf.",
      ],
    },
    {
      type: "section",
      number: "08",
      title: "Your Key Contacts",
    },
    {
      type: "table",
      headers: ["Role", "Name", "Email", "Phone"],
      rows: [
        ["Your Developer", "Keenan Husselmann", "keenan@swiftdesignz.co.za", "+264 81 853 6789"],
        ["Domain & Hosting", "Ambrose (IT-Guru)", "ambrose@it-guru.co.za", "072 962 7608"],
      ],
      colWidths: [20, 25, 35, 20],
    },
    { type: "divider" },
    {
      type: "checklist",
      title: "Your Next Steps \u2014 Right Now",
      items: [
        "Sign and return Proceed to Build (SD-PTB-2026).",
        "Pay the deposit (banking details in PTB document).",
        "Send proof of payment to keenan@swiftdesignz.co.za.",
        "Gather all assets from the checklist above.",
      ],
    },
    {
      type: "checklist",
      title: "Once We Start",
      items: [
        "Watch for preview/draft notification email.",
        "Review within 7 business days.",
        "Submit all feedback in one consolidated list.",
        "Pay final balance before go-live.",
      ],
    },
    { type: "divider" },
    {
      type: "info",
      text: "Thank you for trusting Swift Designz with your project. I\u2019m committed to delivering high-quality work, communicating clearly, and making this a smooth experience from start to finish. \u2014 Keenan",
    },
  ],
};

export const changeRequestForm: TemplateDocument = {
  title: "Change Request",
  subtitle: "Out-of-Scope Work Order",
  ref: "SD-CR-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This form documents any requested changes to the originally agreed scope of work. Out-of-scope work is charged at R350 per hour. Work will not commence until this form is signed and any applicable payment is received.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Change Description",
      bullets: [
        "Feature / Page / Section Affected: _______________________",
        "Change Category: New Feature \u00b7 Content Update \u00b7 Design Change \u00b7 Bug Fix \u00b7 Integration \u00b7 Other",
        "Full Description: _______________________",
        "Reason / Business Justification: _______________________",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Scope & Impact Assessment",
    },
    {
      type: "table",
      headers: ["Assessment", "Detail"],
      rows: [
        ["Scope Classification", "Out of Scope (Billable) / Within Scope / Partially In Scope"],
        ["Priority Level", "Low (No urgency) / Medium (Nice to have soon) / High (Blocking or critical)"],
        ["Estimated Hours", "_______ hours @ R350/hr"],
        ["Estimated Cost", "R _______"],
        ["Timeline Impact", "+ _______ days added to delivery date"],
        ["New Delivery Date", "_______ / _______ / _______"],
        ["Payment Due", "Before work begins / On completion"],
      ],
      colWidths: [35, 65],
    },
    {
      type: "warn",
      text: "Work on this change request will not commence until the client has signed this form AND payment (if applicable) has been received. Any approved change request is an addendum to the original project agreement and is subject to Swift Designz Terms & Conditions (SD-TC-2026).",
    },
    {
      type: "section",
      number: "03",
      title: "Reference / Supporting Materials",
      body: "List any reference links, design mockups, screenshots, or files attached to this request:\n_______________________\n_______________________",
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing below, the client approves the change described above and authorises Swift Designz to proceed. The estimated cost and timeline impact are acknowledged by both parties.",
    },
    { type: "signatures", leftLabel: "Client Approval", rightLabel: "Swift Designz" },
  ],
};

export const proceedToBuild: TemplateDocument = {
  title: "Proceed to Build",
  subtitle: "Project Acceptance & Payment Authorisation",
  ref: "SD-PTB-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This document confirms that the client named below has reviewed and accepted the associated quotation, agrees to all Swift Designz Terms & Conditions, and authorises the project to proceed upon deposit payment. Work will not commence until the deposit is received.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Project Summary",
    },
    {
      type: "table",
      headers: ["Item", "Detail"],
      rows: [
        ["Service Type", "Website / App / E-Commerce / Training"],
        ["Package / Plan", "_______________________"],
        ["Estimated Timeline", "_______________________"],
        ["Project Start Date", "On receipt of deposit"],
        ["Estimated Launch Date", "_______ / _______ / _______"],
        ["Revisions Included", "Up to 3 rounds"],
        ["Quote Reference", "SD-Q-2026-_______"],
      ],
      colWidths: [35, 65],
    },
    {
      type: "section",
      number: "02",
      title: "Agreed Scope of Work",
      body: "Describe the agreed scope, deliverables, and features as per the accepted quotation:\n_______________________\n_______________________\n_______________________",
    },
    {
      type: "section",
      number: "03",
      title: "Payment Schedule",
    },
    {
      type: "table",
      headers: ["Payment", "Amount (R)", "Due Date", "Status"],
      rows: [
        ["Deposit (1st Payment \u2014 50%)", "_______", "On signing this document", "Scheduled"],
        ["2nd Payment (50%)", "_______", "On launch / delivery", "Scheduled"],
        ["3rd Payment (if applicable)", "\u2014", "N/A or Month 3", "Scheduled"],
        ["TOTAL PROJECT VALUE", "_______", "Ref: SD-PTB-2026-___", "EFT Only"],
      ],
      colWidths: [35, 20, 25, 20],
    },
    { type: "banking" },
    {
      type: "section",
      number: "04",
      title: "Key Project Terms (Summary)",
    },
    {
      type: "table",
      headers: ["Term", "Detail"],
      rows: [
        ["Project Start", "Work commences within 24 hours of confirmed deposit receipt"],
        ["Revisions", "Up to 3 rounds included. Additional rounds charged at R350/hour"],
        ["Client Feedback Window", "7 business days per draft. Silence beyond 7 days requires a proxy"],
        ["Assets & Content", "Client-provided assets are free. SD-created assets charged at R350/hr"],
        ["Domain & Hosting", "Managed by IT-Guru (ambrose@it-guru.co.za \u00b7 072 962 7608)"],
        ["Post-Launch Support", "1 month free (2 months for Full Pay). Ongoing: R800/month Retainer"],
        ["Cancellation", "Deposit is non-refundable. Project paused, not cancelled"],
        ["Intellectual Property", "Client owns Shopify store. SD retains code licence for websites/apps"],
        ["Late Payment", "Final payment before handover. Late payment forfeits free support"],
      ],
      colWidths: [30, 70],
    },
    { type: "divider" },
    {
      type: "checklist",
      title: "Client Declarations",
      items: [
        "I have read and understood the quotation and the scope of work described therein.",
        "I agree to the payment schedule above and understand that the deposit is non-refundable.",
        "I accept the Swift Designz Terms & Conditions (SD-TC-2026) in full.",
        "I understand that project work commences only after the deposit is received.",
        "I will provide feedback within 7 business days of receiving each draft.",
        "I understand that final deliverables will only be handed over once all outstanding payments are received.",
        "I understand that Swift Designz retains the right to display this project in their portfolio.",
      ],
    },
    { type: "divider" },
    { type: "signatures", leftLabel: "Client \u2014 Authorised Signature", rightLabel: "Swift Designz" },
  ],
};

export const maintenanceRetainer: TemplateDocument = {
  title: "Maintenance Retainer",
  subtitle: "Ongoing Support Agreement",
  ref: "SD-RET-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "Full access, zero surprises \u2014 one flat rate for peace of mind. The Swift Designz Maintenance Retainer provides ongoing support at R800/month, billed in advance via EFT.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "What\u2019s Included",
      bullets: [
        "Bug Fixes \u2014 Any issues within the original build scope, fixed without additional charges.",
        "Content Updates \u2014 Text, images, pricing, product listings, and general content maintenance.",
        "Security Patches \u2014 Framework updates, dependency patches, and security hardening.",
        "Minor Feature Additions \u2014 Small improvements and tweaks that don\u2019t require a full rebuild.",
        "Performance Checks \u2014 Monthly review of page speed, SEO health, and uptime.",
        "Priority Support \u2014 Retainer clients jump to the front of the queue. Average response within 4 business hours.",
        "Hosting Liaison \u2014 Communication with IT-Guru (or your host) handled on your behalf for maintenance issues.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Not Covered by the Retainer",
      bullets: [
        "Major New Features \u2014 Significant new sections, platforms, or functionality rebuilds (scoped and quoted separately).",
        "New Platform Development \u2014 Building additional apps, stores, or standalone products.",
        "Domain & Hosting Fees \u2014 Costs charged directly by IT-Guru or other hosting providers.",
        "Third-Party Tool Subscriptions \u2014 Shopify fees, plugin licences, API costs, etc.",
        "Training Sessions \u2014 AI or PM training is a separate service. Discounted rate available for retainer clients.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Response Time Service Levels",
    },
    {
      type: "table",
      headers: ["Priority", "Type of Request", "Response Time", "Resolution Target"],
      rows: [
        ["Critical", "Site down, payment gateway broken, data issue", "Within 2 business hours", "Same business day"],
        ["High", "Key feature not working, major content error", "Within 4 business hours", "1\u20132 business days"],
        ["Normal", "Content updates, minor tweaks, general support", "Within 1 business day", "Within 3 business days"],
        ["Low", "Design suggestions, feature requests", "Within 2 business days", "Scheduled into next sprint"],
      ],
      colWidths: [15, 35, 25, 25],
    },
    {
      type: "section",
      number: "04",
      title: "How to Submit a Request",
      bullets: [
        'Step 1: Email keenan@swiftdesignz.co.za with the subject: "Retainer Request \u2014 [Brief Description] \u2014 [Your Name]".',
        "Step 2: Describe the request and attach any screenshots or references.",
        "Step 3: Keenan will confirm receipt and provide an ETA within the applicable SLA window.",
        "Step 4: For out-of-scope requests, a separate Change Request Form (SD-CR-2026) will be issued and quoted before work begins.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Billing & Payment Terms",
    },
    {
      type: "table",
      headers: ["Item", "Detail"],
      rows: [
        ["Monthly Rate", "R800 per calendar month"],
        ["Billing Cycle", "Monthly, billed at the start of each month"],
        ["Payment Method", "EFT only. Banking details on invoice."],
        ["Payment Due", "Within 5 business days of invoice issue"],
        ["Late Payment", "Support suspended until account is current. No penalty fee charged."],
      ],
      colWidths: [30, 70],
    },
    { type: "banking" },
    {
      type: "section",
      number: "06",
      title: "Cancellation Policy",
      body: "Either party may cancel this retainer agreement by providing 30 days\u2019 written notice via email. The retainer will remain active until the end of the 30-day notice period. No partial-month refunds are issued once the billing period has commenced. Swift Designz may terminate this agreement immediately in cases of non-payment, abusive conduct, or breach of the Terms & Conditions (SD-TC-2026).",
    },
    {
      type: "section",
      number: "07",
      title: "Agreement Terms",
      body: "This agreement is subject to Swift Designz Terms & Conditions (SD-TC-2026). By signing below, the client confirms that they understand and accept:",
      bullets: [
        "The retainer is for maintenance and support only \u2014 not for new project development.",
        "Swift Designz retains the right to modify the retainer scope or rate with 30 days\u2019 written notice.",
        "The retainer may be paused by mutual written agreement for periods of 30+ consecutive days.",
      ],
    },
    { type: "divider" },
    { type: "signatures", leftLabel: "Client \u2014 Agreement to Retain", rightLabel: "Swift Designz" },
  ],
};

export const paymentPlanAgreement: TemplateDocument = {
  title: "Payment Plan",
  subtitle: "Flexible Payment Agreement",
  ref: "SD-PP-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This agreement outlines the selected payment plan for the project detailed below. All payments must be made via EFT only. The deposit is non-refundable and project commencement is conditional on its receipt.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Project Value",
      body: "Project Description: _______________________\nTotal Project Value: R _______________________",
    },
    {
      type: "section",
      number: "02",
      title: "Available Payment Plans",
    },
    {
      type: "table",
      headers: ["Plan", "Structure", "Bonus"],
      rows: [
        ["Standard", "50% deposit + 50% on launch", "\u2014"],
        ["Full Pay (Best Value)", "100% upfront on signing", "2 months free support"],
        ["2-Month Flex", "50% deposit + 50% in Month 2", "\u2014"],
        ["3-Month Ease", "50% deposit + 25% Month 2 + 25% Month 3", "\u2014"],
      ],
      colWidths: [25, 45, 30],
    },
    {
      type: "section",
      number: "03",
      title: "Selected Plan & Payment Schedule",
      body: "Selected Plan: _______________________",
    },
    {
      type: "table",
      headers: ["Payment", "Due Date", "Amount (R)", "% of Total"],
      rows: [
        ["1st \u2014 Deposit", "On signing (today)", "_______", "50%"],
        ["2nd Payment", "_______________________", "_______", "_______"],
        ["3rd Payment (if applicable)", "_______________________", "_______", "_______"],
        ["TOTAL", "", "_______", "100%"],
      ],
      colWidths: [30, 30, 20, 20],
    },
    { type: "banking" },
    {
      type: "section",
      number: "04",
      title: "Full Pay Bonus",
      body: "Full Pay clients receive 2 months of free post-launch support instead of the standard 1 month. To qualify, 100% of the total must be received before project commencement.",
    },
    {
      type: "section",
      number: "05",
      title: "Payment Plan Terms",
      bullets: [
        "1. Deposit & Commencement: The deposit (1st payment) is due on the date of signing. Project work commences only upon confirmed receipt. The deposit is non-refundable in all circumstances.",
        "2. Subsequent Payments: Subsequent payments must be made by the agreed due dates. Failure to pay on the agreed date will result in the project being paused until payment is received.",
        "3. Late Payment Consequence: Any payment 5 or more business days overdue will result in forfeiture of the 1-month free support period. Work will not be delivered or launched until all outstanding amounts are settled.",
        "4. Plan Modification: Payment plan modifications (e.g. changing from 2-Month to 3-Month) may be requested in writing before the 2nd payment is due. Swift Designz reserves the right to accept or decline.",
        "5. Maximum Plan Duration: Payment plans are available for a maximum of 3 months from project acceptance. Longer timelines must be negotiated separately.",
        "6. Currency & Method: All payments are in ZAR/NAD (R) via EFT only. Proof of payment must be emailed to keenan@swiftdesignz.co.za.",
      ],
    },
    { type: "divider" },
    { type: "signatures", leftLabel: "Client", rightLabel: "Swift Designz" },
  ],
};

export const projectHandover: TemplateDocument = {
  title: "Project Handover",
  subtitle: "Delivery & Completion Certificate",
  ref: "SD-HO-2026",
  version: "1.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This document certifies that the project described below has been delivered as per the agreed scope of work. It serves as the official completion certificate and includes delivery checklists, credentials handover, and post-launch support details.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Project Details",
    },
    {
      type: "table",
      headers: ["Item", "Detail"],
      rows: [
        ["Service Type", "Website / E-Commerce / App / Training"],
        ["Package", "Starter / Professional / Premium"],
        ["Project Reference", "SD-PTB-2026-_______"],
        ["Final Delivery URL", "https://_______________________"],
        ["Handover Date", "_______ / _______ / _______"],
      ],
      colWidths: [35, 65],
    },
    {
      type: "section",
      number: "02",
      title: "Core Delivery Checklist",
    },
    {
      type: "checklist",
      items: [
        "Live URL / deployed application accessible.",
        "All agreed pages / features implemented and functional.",
        "Mobile responsiveness verified (phone, tablet, desktop).",
        "Cross-browser testing completed (Chrome, Firefox, Safari, Edge).",
        "All content, images, and media uploaded and displaying correctly.",
        "Contact forms and integrations tested and working.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Technical & SEO Checklist",
    },
    {
      type: "checklist",
      items: [
        "SSL certificate active (HTTPS confirmed).",
        "Sitemap submitted to Google Search Console.",
        "Google Analytics / tracking set up and verified.",
        "Page speed / Lighthouse score reviewed (target: 80+).",
        "robots.txt and meta descriptions in place.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "E-Commerce Checklist (if applicable)",
    },
    {
      type: "checklist",
      items: [
        "Checkout flow tested end-to-end (including payment).",
        "All products imported and displaying with correct prices.",
        "Shipping, tax, and order confirmation emails configured.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Credentials & Access Handover",
      body: "All credentials are provided via a separate secure channel (password manager or encrypted message). Passwords are never included in this document for security reasons.",
    },
    {
      type: "table",
      headers: ["Platform / Tool", "URL / Location", "Access Notes"],
      rows: [
        ["Website / CMS", "https://_______________________", "Admin credentials sent separately"],
        ["Hosting (IT-Guru)", "https://it-guru.co.za", "Contact Ambrose for client account"],
        ["Domain Registrar", "_______________________", "Login sent separately"],
        ["Google Analytics", "analytics.google.com", "Invite sent to client email"],
        ["Source Code", "Per IP terms in SD-TC-2026", "Licence granted on full payment"],
        ["Other", "_______________________", "_______________________"],
      ],
      colWidths: [25, 40, 35],
    },
    {
      type: "warn",
      text: "Store all credentials securely using a password manager. Change default passwords immediately after receiving them. Do not share credentials via email or unencrypted channels.",
    },
    {
      type: "section",
      number: "06",
      title: "Files & Assets Delivered",
    },
    {
      type: "checklist",
      items: [
        "Source Code (as per IP terms).",
        "Design Files (Figma / PSD).",
        "Final Assets Pack (images, icons, media).",
        "Logo Files (all formats).",
        "Training Materials (if applicable).",
        "User Manual / Guide.",
        "API Documentation (if applicable).",
        "Database Schema (if applicable).",
        "Session Recordings (if consented).",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Post-Launch Support Period",
    },
    {
      type: "table",
      headers: ["Item", "Detail"],
      rows: [
        ["Free Support Starts", "_______ / _______ / _______ (date of delivery)"],
        ["Free Support Ends", "_______ / _______ / _______ (1 month Standard / 2 months Full Pay)"],
        ["Payment Plan Used", "Standard / Full Pay"],
      ],
      colWidths: [35, 65],
    },
    {
      type: "info",
      text: "After your free support period, maintain priority access to Swift Designz for R800/month \u2014 covering bug fixes, content updates, security patches, and more. See Maintenance Retainer Agreement (SD-RET-2026).",
    },
    {
      type: "section",
      number: "08",
      title: "Client Training & Verification",
    },
    {
      type: "checklist",
      items: [
        "Client has been walked through the live site / system.",
        "CMS / admin panel access demonstrated.",
        "Client has confirmed correct receipt of all credentials.",
        "Client has verified the live site / product meets scope.",
        "Final invoice paid and receipt issued.",
      ],
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing below, the client confirms that the project has been delivered as per the agreed scope, all credentials and files have been received, and the post-launch support period has commenced.",
    },
    { type: "signatures", leftLabel: "Client \u2014 Delivery Acceptance", rightLabel: "Swift Designz \u2014 Delivered By" },
  ],
};

export const estoreRetainer: TemplateDocument = {
  title: "eStore Retainer Agreement",
  subtitle: "Monthly eCommerce Management Contract",
  ref: "SD-ESR-2026",
  version: "1.0",
  effective: "May 2026",
  blocks: [
    {
      type: "info",
      text: "This eStore Retainer Agreement (\u201cAgreement\u201d) is entered into between Keenan Husselmann, trading as Swift Designz (\u201cService Provider\u201d), and the client identified below (\u201cClient\u201d). This Agreement governs the ongoing management and support of the Client\u2019s eCommerce store at a fixed monthly retainer rate of R1,200 per month, subject to the terms outlined herein.",
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Retainer Rate & Scope",
      body: "The monthly retainer fee is R1,200 (One Thousand Two Hundred Rand) per calendar month. This flat rate covers the following services:",
      bullets: [
        "Product Management \u2014 Adding, editing, and removing products including descriptions, pricing, variants, and collections.",
        "Image Generation \u2014 Creation and optimisation of product and banner images suitable for the store.",
        "Automation \u2014 Setting up and maintaining store automations, flows, and triggers to streamline operations.",
        "Theme Editing \u2014 Visual and layout adjustments to the store theme, including colour, typography, section layout, and responsiveness.",
        "24-Hour Maintenance & Support \u2014 Monitoring of the store for issues, bugs, and downtime with rapid response within 24 hours.",
        "Training \u2014 Guidance and training sessions to help the Client or their team manage and operate the store effectively.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Services Not Included",
      body: "The following services fall outside the scope of this retainer. They may be engaged as separate once-off services quoted independently, or the Client may request an upgraded retainer plan to include applicable services:",
      bullets: [
        "Inventory Management \u2014 Full stock control, supplier coordination, purchase order management, and inventory reconciliation.",
        "Cost Management \u2014 Margin analysis, cost-of-goods tracking, financial reporting, and pricing strategy.",
        "Payment Gateway Integration \u2014 See Section 03 for the specific terms governing payment gateway work.",
        "Product Research \u2014 Market research, competitor analysis, niche sourcing, and new product identification.",
        "Advertising \u2014 Paid media campaigns (Google Ads, Meta Ads, TikTok Ads, etc.), ad creative, and budget management.",
        "Social Media Promotion \u2014 Content creation, scheduling, community management, and organic social growth strategies.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Payment Gateway Integration",
      body: "Payment gateway integration is a specialised service governed by the following terms:",
      bullets: [
        "Integration is treated as a once-off project and will be scoped and quoted separately from this retainer.",
        "A separate invoice will be issued for the once-off integration setup fee prior to commencement of that work.",
        "Following successful integration, the monthly retainer rate will increase to account for ongoing payment gateway management and monitoring.",
        "The revised retainer rate post-integration will be communicated in writing and agreed upon before integration work begins.",
        "Swift Designz does not accept liability for gateway provider outages, fee changes, or third-party compliance requirements (e.g. PCI-DSS).",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Service Level & Response Times",
    },
    {
      type: "table",
      headers: ["Priority", "Issue Type", "Response Target", "Resolution Target"],
      rows: [
        ["Critical", "Store down, checkout broken, payment failure", "Within 4 hours", "Same day"],
        ["High", "Product errors, major display issues", "Within 8 hours", "Within 1 business day"],
        ["Normal", "Content updates, automation changes, theme edits", "Within 24 hours", "Within 2\u20133 business days"],
        ["Low", "Training requests, feature suggestions", "Within 2 business days", "Scheduled by agreement"],
      ],
      colWidths: [15, 35, 25, 25],
    },
    {
      type: "section",
      number: "05",
      title: "Payment Terms",
    },
    {
      type: "table",
      headers: ["Item", "Detail"],
      rows: [
        ["Monthly Rate", "R1,200 per calendar month"],
        ["Payment Due Date", "Client\u2019s elected date: 1st or last calendar day of each month (confirmed at sign-up)"],
        ["Payment Method", "EFT only. Banking details provided on each invoice. Reference must include the invoice number."],
        ["Grace Period", "3 calendar days from the due date"],
        ["Late Payment Consequence", "Services will be paused after 3 days without payment. Work resumes upon receipt of outstanding amount."],
        ["VAT", "Swift Designz is not VAT registered. No VAT is charged."],
      ],
      colWidths: [30, 70],
    },
    { type: "banking" },
    {
      type: "section",
      number: "06",
      title: "Contract Duration & Renewal",
      bullets: [
        "This Agreement is valid for an initial fixed term of 12 (twelve) calendar months from the date of signing.",
        "Upon expiry of the initial term, this Agreement will automatically renew on a rolling monthly basis under the same terms, unless either party provides written notice of cancellation in accordance with Section 07.",
        "Swift Designz reserves the right to review and adjust the retainer rate at any renewal point. Any rate change will be communicated in writing at least 30 days before the new rate takes effect.",
        "The Client may accept the revised rate or exercise their right to cancel in accordance with Section 07.",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Cancellation & Early Exit",
      bullets: [
        "Either party may cancel this Agreement by providing 30 (thirty) days\u2019 written notice via email to keenan@swiftdesignz.co.za.",
        "The retainer remains active and payable throughout the 30-day notice period. No partial-month refunds are issued.",
        "Clients who opt out before the end of the initial 12-month fixed term will lose their retainer pricing. All future services will default to individually scoped and priced quotations at standard Swift Designz rates.",
        "Swift Designz may terminate this Agreement immediately and without notice in cases of: non-payment beyond 14 calendar days, abusive or threatening conduct, or material breach of these terms.",
        "Upon termination, Swift Designz will provide the Client with access to all assets, content, and store credentials created or managed under this retainer within 5 business days.",
      ],
    },
    {
      type: "section",
      number: "08",
      title: "Retainer Upgrades & Scope Changes",
      bullets: [
        "The Client may request an upgrade to their retainer plan at any time to include additional services from Section 02.",
        "Upgrades are subject to availability and will be quoted in writing before taking effect.",
        "An upgraded retainer will result in a revised monthly rate, agreed in writing by both parties before the change is activated.",
        "Out-of-scope requests that are not covered by an upgrade will be quoted separately as once-off services.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Client Responsibilities",
      bullets: [
        "The Client must provide timely access to their store backend, credentials, and any third-party tools required to deliver the retainer services.",
        "The Client is responsible for the accuracy of all product information, pricing, and content they supply.",
        "The Client must notify Swift Designz of any planned promotions, campaigns, or high-traffic events at least 5 business days in advance to allow for preparation.",
        "The Client is responsible for all third-party subscription costs (e.g. Shopify plan fees, app subscriptions, theme licences). These are not covered by the retainer.",
        "The Client must respond to queries or requests for approval within 3 business days. Delays caused by unresponsiveness are excluded from response time SLAs.",
      ],
    },
    {
      type: "section",
      number: "10",
      title: "Intellectual Property",
      bullets: [
        "All work produced under this retainer (images, copy, automations, theme edits) that is created by Swift Designz becomes the property of the Client upon full payment of the applicable monthly invoice.",
        "Swift Designz retains the right to display retainer work in its portfolio unless the Client opts out in writing.",
        "The Client\u2019s store, brand assets, products, and data remain exclusively the property of the Client at all times.",
      ],
    },
    {
      type: "section",
      number: "11",
      title: "Limitation of Liability",
      bullets: [
        "Swift Designz is not liable for losses arising from platform outages, third-party app failures, payment gateway issues, or events outside its direct control.",
        "Swift Designz is not responsible for changes made to the store by the Client or any third party outside of this Agreement.",
        "The total liability of Swift Designz under this Agreement shall not exceed the total retainer fees paid in the 3 months preceding the event giving rise to the claim.",
        "Swift Designz does not guarantee specific sales outcomes, conversion rates, or revenue results from any work performed under this retainer.",
      ],
    },
    {
      type: "section",
      number: "12",
      title: "General Terms",
      bullets: [
        "This Agreement is governed by the laws of the Republic of South Africa.",
        "This Agreement constitutes the entire agreement between the parties regarding the eStore retainer and supersedes any prior verbal or written discussions.",
        "Amendments to this Agreement must be made in writing and signed by both parties.",
        "Swift Designz may subcontract elements of this retainer to trusted partners without prior Client approval, provided the quality and confidentiality standards of this Agreement are maintained.",
        "This Agreement is subject to Swift Designz Terms & Conditions (SD-TC-2026), which are incorporated by reference.",
      ],
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing below, both parties confirm that they have read, understood, and agree to the terms of this eStore Retainer Agreement. This Agreement becomes binding on the date of the last signature below.",
    },
    { type: "signatures", leftLabel: "Client \u2014 Acceptance of Retainer", rightLabel: "Swift Designz \u2014 Service Provider" },
  ]
};
