"use server";

import Anthropic from "@anthropic-ai/sdk";
import { requireAuth } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { buildSystemPrompt } from "@/lib/marketing-context";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const TASK_PROMPTS: Record<string, string> = {
  caption:   "Write a social media caption for the platform specified. Include relevant hashtags at the end. Plain text only — no HTML.",
  campaign:  "Generate a campaign concept including: campaign name, goal, key message, and 3 post ideas. Plain text only — no HTML.",
  email:     "Write a marketing email as plain text copy only — no HTML, no code, no tags. Output exactly three sections:\n\n**Subject:** (the subject line)\n**Preview:** (the preview text, max 90 chars)\n**Body:** (the full email body as readable prose with short paragraphs)",
  hashtags:  "Generate 20 relevant hashtags — mix broad, niche, and location-specific. Group by category. Plain text only — no HTML.",
  headline:  "Write 5 compelling ad headline variations (under 30 characters each) for this brief. Plain text only — no HTML.",
  cta:       "Write 5 strong call-to-action variations for this brief. Be direct and action-oriented. Plain text only — no HTML.",
};

export async function generateMarketingCopyAction(formData: FormData): Promise<
  { content: string } | { error: string }
> {
  await requireAuth();

  const task     = (formData.get("task") as string)     ?? "caption";
  const platform = (formData.get("platform") as string) ?? "instagram";
  const brief    = (formData.get("brief") as string)    ?? "";

  if (!brief.trim()) return { error: "Brief is required." };

  const taskPrompt = TASK_PROMPTS[task] ?? TASK_PROMPTS.caption;

  const userMessage = `Task: ${taskPrompt}
Platform: ${platform}
Brief: ${brief}`;

  try {
    const message = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 1024,
      system: buildSystemPrompt(),
      messages: [{ role: "user", content: userMessage }],
    });

    const text = message.content
      .filter((b) => b.type === "text")
      .map((b) => (b as { type: "text"; text: string }).text)
      .join("\n");

    return { content: text };
  } catch (err) {
    console.error("Anthropic error:", err);
    return { error: "AI generation failed. Check ANTHROPIC_API_KEY." };
  }
}

export async function saveDraftPostAction(formData: FormData): Promise<{ ok: true } | { error: string }> {
  await requireAuth();
  const supabase = await createClient();

  const title    = (formData.get("title") as string)    ?? "AI Draft";
  const content  = (formData.get("content") as string)  ?? "";
  const platform = (formData.get("platform") as string) ?? "other";

  const { error } = await supabase.from("content_posts").insert({
    title,
    content,
    platform,
    status:       "draft",
    notes:        "Generated by AI marketing agent",
    scheduled_at: null,
    campaign_id:  null,
  });

  if (error) return { error: error.message };
  revalidatePath("/marketing/calendar");
  return { ok: true };
}
